services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      # - redis
    environment:
      - GIN_MODE=${GIN_MODE:-release}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: ./
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
volumes:
  pgdata:
  cloudbeaver:
