
// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
  "swagger": "2.0",
  "info": {
    "description": "Auto-generated API documentation",
    "title": "Auto Myself API",
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/v0",
  "schemes": ["http"]
}`

func init() {
    swag.Register("swagger", &s)
}

var s = swag.Spec{
    Version:          "1.0",
    Host:             "localhost:8080",
    BasePath:         "/v0",
    InfoInstanceName: "swagger",
    SwaggerTemplate:  docTemplate_swagger,
    LeftDelim:        "{{",
    RightDelim:       "}}",
}
